version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - .env.prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file: 
      - .env.prod
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/static
    command: sh -c "pdm run python manage.py migrate &&
                    pdm run python manage.py collectstatic --noinput &&
                    pdm run uvicorn test_task.asgi:application --host 0.0.0.0 --port 8000"
  server:
    depends_on:
      - app
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/web/static

volumes:
  static_volume:
  postgres_data: