version: "3"

services:
  db:
    image: postgres:latest
    env_file:
      - .env
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_PASSWORD
      - DATABASE_HOST
      - DATABASE_PORT
      - SECRET_KEY
      - STRIPE_KEY
    ports:
      - 8000:8000
    command: sh -c "pdm run python manage.py migrate && pdm run dev"