# Generated by Django 4.1.6 on 2023-02-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="currency",
            field=models.CharField(
                choices=[("USD", "$"), ("RUB", "₽")], default="USD", max_length=3
            ),
        ),
    ]
