# Generated by Django 4.1.6 on 2023-02-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_tax_order_taxes"),
    ]

    operations = [
        migrations.AddField(
            model_name="tax",
            name="stripe_id",
            field=models.CharField(editable=False, max_length=500, null=True),
        ),
    ]
