# Generated by Django 4.1.6 on 2023-02-10 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_order_discounts_alter_order_taxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="percent_off",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(75),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discounts",
            field=models.ManyToManyField(blank=True, null=True, to="orders.discount"),
        ),
        migrations.AlterField(
            model_name="order",
            name="taxes",
            field=models.ManyToManyField(blank=True, null=True, to="orders.tax"),
        ),
    ]
